#pragma once

// Header with meta info generated by CMake.
#include "SourceRes_Config.h"

// Required SDK headers.
#define CLIENT_DLL
#include "tier1/tier1.h"
#include "cbase.h"


// https://stackoverflow.com/questions/5459868/concatenate-int-to-string-using-c-preprocessor/5459929#5459929
#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define PLUGIN_DESC "SourceRes " STR(SourceRes_VERSION_MAJOR) "." STR(SourceRes_VERSION_MINOR)


// Our handle to the game engine.
IVEngineClient *engine;


class SequencePlugin : public IServerPluginCallbacks
{
public:
	SequencePlugin();
	~SequencePlugin();

	virtual bool			Load(CreateInterfaceFn interfaceFactory, CreateInterfaceFn gameServerFactory);
	virtual void			Unload(void);
	virtual void			Pause(void);
	virtual void			UnPause(void);
	virtual const char     *GetPluginDescription(void);
	virtual void			LevelInit(char const *pMapName);
	virtual void			ServerActivate(edict_t *pEdictList, int edictCount, int clientMax);
	virtual void			GameFrame(bool simulating);
	virtual void			LevelShutdown(void);
	virtual void			ClientActive(edict_t *pEntity);
	virtual void			ClientDisconnect(edict_t *pEntity);
	virtual void			ClientPutInServer(edict_t *pEntity, char const *playername);
	virtual void			SetCommandClient(int index);
	virtual void			ClientSettingsChanged(edict_t *pEdict);
	virtual PLUGIN_RESULT	ClientConnect(bool *bAllowConnect, edict_t *pEntity, const char *pszName, const char *pszAddress, char *reject, int maxrejectlen);
	virtual PLUGIN_RESULT	ClientCommand(edict_t *pEntity, const CCommand &args);
	virtual PLUGIN_RESULT	NetworkIDValidated(const char *pszUserName, const char *pszNetworkID);
	virtual void			OnQueryCvarValueFinished(QueryCvarCookie_t iCookie, edict_t *pPlayerEntity, EQueryCvarValueStatus eStatus, const char *pCvarName, const char *pCvarValue);
	virtual void			OnEdictAllocated(edict_t *edict);
	virtual void			OnEdictFreed(const edict_t *edict);
};
